package io.github.vooft.spektor.codegen.codegen

object ResponseStatusClassNameGenerator {

    fun generate(status: Int): String = STATUS_CLASS_NAMES[status] ?: "Status$status"

    private val STATUS_CLASS_NAMES = mapOf(
        100 to "Continue",
        101 to "SwitchingProtocols",
        102 to "Processing",
        200 to "Ok",
        201 to "Created",
        202 to "Accepted",
        203 to "NonAuthoritativeInformation",
        204 to "NoContent",
        205 to "ResetContent",
        206 to "PartialContent",
        207 to "MultiStatus",
        300 to "MultipleChoices",
        301 to "MovedPermanently",
        302 to "Found",
        303 to "SeeOther",
        304 to "NotModified",
        305 to "UseProxy",
        306 to "SwitchProxy",
        307 to "TemporaryRedirect",
        308 to "PermanentRedirect",
        400 to "BadRequest",
        401 to "Unauthorized",
        402 to "PaymentRequired",
        403 to "Forbidden",
        404 to "NotFound",
        405 to "MethodNotAllowed",
        406 to "NotAcceptable",
        407 to "ProxyAuthenticationRequired",
        408 to "RequestTimeout",
        409 to "Conflict",
        410 to "Gone",
        411 to "LengthRequired",
        412 to "PreconditionFailed",
        413 to "PayloadTooLarge",
        414 to "RequestUriTooLong",
        415 to "UnsupportedMediaType",
        416 to "RequestedRangeNotSatisfiable",
        417 to "ExpectationFailed",
        422 to "UnprocessableEntity",
        423 to "Locked",
        424 to "FailedDependency",
        425 to "TooEarly",
        426 to "UpgradeRequired",
        429 to "TooManyRequests",
        431 to "RequestHeaderFieldTooLarge",
        500 to "InternalServerError",
        501 to "NotImplemented",
        502 to "BadGateway",
        503 to "ServiceUnavailable",
        504 to "GatewayTimeout",
        505 to "VersionNotSupported",
        506 to "VariantAlsoNegotiates",
        507 to "InsufficientStorage",
    )
}
