openapi: 3.1.0
info:
  title: Book API
  version: 1.0.0
paths:
  /book/{id}:
    delete:
      tags:
        - Book
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Book was deleted
  /book/{id}/optional-update:
    post:
      tags:
        - Book
      operationId: optionalUpdate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '../models/book.yaml#/components/schemas/BookUpdateRequest'
      responses:
        200:
          description: Book was updated
  /book:
    post:
      tags:
        - Book
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../models/book.yaml#/components/schemas/BookRequest'
      responses:
        200:
          description: Model was created
          content:
            application/json:
              schema:
                $ref: '../models/book.yaml#/components/schemas/Book'
