openapi: 3.1.0
info:
  title: Owner API
  version: 1.0.0
paths:
  /owner:
    get:
      tags:
        - Owner
      operationId: list
      responses:
        200:
          description: List is returned
          content:
            application/json:
              schema:
                $ref: '../models/owner.yaml#/components/schemas/OwnersList'
