openapi: 3.0.1
info:
  title: Author API
  version: 1.0.0
paths:
  /author/{id}:
    get:
      tags:
        - Author
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Retrieved by id
          content:
            application/json:
              schema:
                $ref: '../models/author.yaml#/components/schemas/Author'
