openapi: 3.1.0
info:
  title: Upload API
  version: 1.0.0
paths:
  /uploads:
    post:
      tags:
        - Upload
      operationId: upload
      requestBody:
        required: true
        content:
          '*/*': { }
      responses:
        200:
          description: Uploaded file info
          content:
            application/json:
              schema:
                $ref: '../models/uploadedFile.yaml#/components/schemas/UploadedFile'
