openapi: 3.0.1
info:
  title: Author Models
  version: 1.0.0
paths: { }
components:
  schemas:
    AuthorCountry:
      type: string
      enum: [US, DE, JP]
    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        dateOfBirth:
          type: string
          format: date
        dateOfDeath:
          type: string
          format: date
        country:
          $ref: '#/components/schemas/AuthorCountry'
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - dateOfBirth
        - country
        - createdAt
    AuthorsList:
      type: object
      properties:
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
      required:
        - authors
    AuthorRequest:
      type: object
      properties:
        name:
          type: string
        dateOfBirth:
          type: string
          format: date
        country:
          $ref: '#/components/schemas/AuthorCountry'
        dateOfDeath:
          type: string
          format: date
      required:
        - name
        - dateOfBirth
        - country

