openapi: 3.0.1
info:
  title: Book Models
  version: 1.0.0
paths: { }
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        nativeTitle:
          type: string
        author:
          $ref: "./author.yaml#/components/schemas/Author"
        price:
          $ref: "./money.yaml#/components/schemas/Money"
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - title
        - author
        - createdAt
    BooksList:
      type: object
      properties:
        books:
          type: array
          items:
            $ref: '#/components/schemas/Book'
      required:
        - books
    BookRequest:
      type: object
      properties:
        title:
          type: string
        nativeTitle:
          type: string
        authorId:
          type: string
          format: uuid
        price:
          $ref: "./money.yaml#/components/schemas/Money"
      required:
        - title
        - authorId

