openapi: 3.1.0
info:
  title: Book Models
  version: 1.0.0
paths: { }
components:
  schemas:
    CountryPrices:
      title: CountryPrices
      type: object
      propertyNames:
        $ref: "./country.yaml#/components/schemas/Country"
      additionalProperties:
        $ref: "./money.yaml#/components/schemas/Money"

