openapi: 3.1.0
info:
  title: Event Models
  version: 1.0.0
paths: { }
components:
  schemas:
    EventType:
      title: EventType
      type: string
      enum:
        - CLICK
        - PING
    Event:
      title: Event
      oneOf:
        - $ref: '#/components/schemas/ClickEvent'
        - $ref: '#/components/schemas/PingEvent'
      discriminator:
        propertyName: type
        mapping:
          CLICK: '#/components/schemas/ClickEvent'
          PING: '#/components/schemas/PingEvent'
    ClickEvent:
      title: ClickEvent
      type: object
      properties:
        type:
          $ref: '#/components/schemas/EventType'
        x:
          type: integer
        y:
          type: integer
      required:
        - type
        - x
        - y
    PingEvent:
      title: PingEvent
      type: object
      properties:
        type:
          $ref: '#/components/schemas/EventType'
      required:
        - type
    EventsList:
      title: EventsList
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
      required:
        - events
