openapi: 3.1.0
info:
  title: Money Models
  version: 1.0.0
paths: { }
components:
  schemas:
    Money:
      title: Money
      type: object
      properties:
        minorUnits:
          type: integer
        currency:
          type: string
      required:
        - minorUnits
        - currency

