openapi: 3.1.0
info:
  title: Notification Models
  version: 1.0.0
paths: { }
components:
  schemas:
    NotificationChannel:
      description: Notification Channel
      type: string
      enum:
        - PUSH
        - SMS
    NotificationCategory:
      description: Notification Category
      type: string
      enum:
        - CARD_PAYMENT
        - REWARDS
    NotificationCategories:
      description: Notification Categories
      type: object
      propertyNames:
        $ref: '#/components/schemas/NotificationCategory'
      additionalProperties:
        type: boolean
    NotificationSettings:
      description: Notification Settings
      type: object
      #propertyNames skipped intentionally to test the default value
      additionalProperties:
        $ref: '#/components/schemas/NotificationCategories'


